#+TITLE: bmv - Batch Move
#+AUTHOR: Alex Sun (ranmaru22)

*Rename large numbers of files easily.*

*bmv* is a Regex-based move/rename tool that can handle many files and directories
at once.

* Usage
bmv commands are formend in a /from-to/ pattern, similar to ~sed~ but in a simpler
way. For example, ~sed -i 's/foo/bar/' <files>~ would be ~bmv 'foo' 'bar' <files>~
in bmv. The replacement is then done across /all/ matches.

** Examples
/tbd/

** It does not match hidden files when using globs!
bmv by itself does not handle resolving the glob, it just receives a list of
files it's supposed to operate on from standard input. So in order to include
hidden files, you need to make sure the shell you're using includes them into
your glob. In =zsh= this can easily be done by using the ~(D)~ modifier.

#+begin_src sh
  bmv 'foo' 'bar' ./**/*(D)
#+end_src

In =bash= you can set ~dotglob~.

* Installation
** Manually from source
You need to have Rust and Cargo installed.

#+begin_src sh
  git clone https://github.com/ranmaru22/bmv.git
  cd bmv
  cargo install --locked --path=.
#+end_src

This will install the =master= branch which has the latest stable release. If you
want the development version, switch to branch =develop=.

#+begin_src sh
  git checkout develop
#+end_src

** From the Cargo registry
You need to have Rust and Cargo installed.

#+begin_src sh
  cargo install bmv --locked
#+end_src

** From a package manager
/tbd/


* Disclaimer
bmv is provided as-is and with no warranty. I developed it for mostly personal
use, so it likely has some gotchas and bugs. Feel free to hack it (and if you
like, send back a PR, I will happily include any improvements) but use it at
your onw risk.
