---
name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
    test:
      name: Check & Test
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          rust: [stable]
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout source
          uses: actions/checkout@v2

        - name: Install stable toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: ${{ matrix.rust }}
            override: true

        - uses: Swatinem/rust-cache@v1

        - name: Cargo clippy
          uses: actions-rs/cargo@v1
          with:
            command: clippy
            args: -- -D warnings

        - name: Cargo test
          uses: actions-rs/cargo@v1
          with:
            command: test
